import 'package:drift/drift.dart';
import 'package:drift_flutter/drift_flutter.dart';

import '../config/app_constants.dart';
import '../sync/sync_status.dart';
import 'daos/responses_dao.dart';
import 'daos/surveys_dao.dart';
import 'tables/survey_responses_table.dart';
import 'tables/surveys_table.dart';

// Generated by build_runner (drift_dev). Run:
//   dart run build_runner build --delete-conflicting-outputs
part 'app_database.g.dart';

/// The app's local SQLite database — the **single source of truth** the UI
/// always reads from. The REST API only ever feeds this database (on download)
/// or is fed by it (on sync); screens never talk to the network directly.
@DriftDatabase(
  tables: [Surveys, SurveyResponses],
  daos: [SurveysDao, ResponsesDao],
)
class AppDatabase extends _$AppDatabase {
  /// Production constructor opens the on-disk database file.
  AppDatabase() : super(_openConnection());

  /// Test constructor — pass an in-memory executor from tests.
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        // Future schema changes are handled here (onUpgrade) as versions grow.
      );

  static QueryExecutor _openConnection() => driftDatabase(
        name: AppConstants.databaseName,
        // Required for the web build: these files live in web/ (downloaded from
        // the drift + sqlite3.dart releases). Ignored on native platforms.
        web: DriftWebOptions(
          sqlite3Wasm: Uri.parse('sqlite3.wasm'),
          driftWorker: Uri.parse('drift_worker.js'),
        ),
      );
}
